# Generated by Django 4.2.2 on 2023-07-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('siglas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LocalRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrioRepuesto', to='locales.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaRepuesto', to='locales.persona')),
            ],
        ),
        migrations.CreateModel(
            name='LocalComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=80)),
                ('tipoComida', models.CharField(max_length=80)),
                ('ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrioComida', to='locales.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaComida', to='locales.persona')),
            ],
        ),
    ]
